In [1]:
import numpy as np


In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [16]:
b = np.array([0,2,3,6,8,9])
b

array([0, 2, 3, 6, 8, 9])

In [6]:
a[0],a[1]

(np.int64(1), np.int64(2))

In [7]:
a[0:]

array([1, 2, 3, 4, 5])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3, 4])

In [10]:
a[::2]

array([1, 3, 5])

In [11]:
b[0],b[2],b[-1]

(np.int64(0), np.int64(6), np.int64(9))

In [18]:
b[[0,2,-1]]

array([0, 3, 9])

Array Type

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
a.dtype

dtype('int64')

In [22]:
b

array([0, 2, 3, 6, 8, 9])

In [23]:
b.dtype

dtype('int64')

In [28]:
np.array([1,2,3,4,5],dtype = np.int8)

array([1, 2, 3, 4, 5], dtype=int8)

Dimensions and shapes

In [29]:
A = np.array([
    [1,2,3],
    [5,6,7]
])

In [30]:
A.shape

(2, 3)

In [31]:
A.ndim

2

In [32]:
A.size

6

In [33]:
B = np.array([
    [
        [1,2,3],
        [6,7,8]
     ],
     [
        [12,34,56],
        [78,89,78]
     ]
])

In [34]:
B

array([[[ 1,  2,  3],
        [ 6,  7,  8]],

       [[12, 34, 56],
        [78, 89, 78]]])

In [35]:
B.shape

(2, 2, 3)

In [36]:
B.ndim

3

In [37]:
B.size

12